// AUDITED-OUT LEDGER (generated 2026-07-12, JZ_AUDIT bypass sweep).
// Every file here was RUN with its family skip bypassed and FAILED — each is
// out of the jz value model for the stated reason ("know every fail by face").
// Everything else those families used to blanket now runs. Regenerate by
// re-running the JZ_AUDIT sweep after landing a feature that shrinks a family.
export const AUDITED_OUT = new Map([
  ['test/language/expressions/async-arrow-function/async-lineterminator-identifier-throws.js', 'async [no LineTerminator] restricted production not enforced (recorded divergence)'],
  ['test/language/statements/async-function/syntax-declaration-no-line-terminator.js', 'async [no LineTerminator] restricted production not enforced (recorded divergence)'],
  ['test/language/statements/using/block-local-closure-get-before-initialization.js', 'TDZ ReferenceError not synthesized (permissive by design)'],
  ['test/language/statements/using/block-local-use-before-initialization-in-prior-statement.js', 'TDZ ReferenceError not synthesized (permissive by design)'],
  ['test/language/statements/using/function-local-closure-get-before-initialization.js', 'TDZ ReferenceError not synthesized (permissive by design)'],
  ['test/language/statements/using/function-local-use-before-initialization-in-prior-statement.js', 'TDZ ReferenceError not synthesized (permissive by design)'],
  ['test/language/statements/using/global-closure-get-before-initialization.js', 'TDZ ReferenceError not synthesized (permissive by design)'],
  ['test/language/statements/using/initializer-disposed-at-end-of-generatorbody.js', 'using across generator suspension outside v1'],
  ['test/language/statements/using/syntax/using-declaring-let-split-across-two-lines.js', 'using [no LineTerminator] restriction not enforced (recorded divergence)'],
  ['test/language/statements/using/syntax/using-for-statement.js', 'using in for-statement heads outside the jzify lowering'],
  ['test/language/statements/using/syntax/using-invalid-assignment-next-expression-for.js', 'using in for-statement heads outside the jzify lowering'],
  ['test/language/statements/using/syntax/using-invalid-assignment-statement-body-for-of.js', 'using in for-statement heads outside the jzify lowering'],
  ['test/language/statements/using/syntax/using-outer-inner-using-bindings.js', 'using in for-statement heads outside the jzify lowering'],
  ['test/language/statements/using/throws-if-initializer-Symbol.dispose-property-not-callable.js', 'dispose callability check (v1 checks presence only)'],
  ['test/language/statements/using/throws-suppressederror-if-multiple-errors-during-disposal.js', 'no SuppressedError aggregation (documented divergence)'],
  ['test/language/computed-property-names/class/static/generator-prototype.js', 'generator reflection outside jzify subset'],
  ['test/language/expressions/array/spread-err-mult-err-expr-throws.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-err-mult-err-itr-get-call.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-err-mult-err-itr-step.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-err-sngl-err-expr-throws.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-err-sngl-err-itr-get-call.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-err-sngl-err-itr-get-value.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-err-sngl-err-itr-step.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-mult-empty.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-mult-expr.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-mult-iter.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-mult-literal.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-mult-obj-null.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-mult-obj-undefined.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-obj-mult-spread.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-obj-null.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-obj-overrides-prev-properties.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-obj-symbol-property.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-obj-undefined.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-obj-with-overrides.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-sngl-empty.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-sngl-expr.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/array/spread-sngl-iter.js', 'spread drives the iterator protocol (indexed model)'],
  ['test/language/expressions/array/spread-sngl-literal.js', 'spread iterator protocol unsupported'],
  ['test/language/expressions/arrow-function/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/arrow-function/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/arrow-function/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/arrow-function/dstr/ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/arrow-function/dstr/ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/arrow-function/dstr/ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/arrow-function/dstr/ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/arrow-function/dstr/ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/arrow-function/dstr/dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/arrow-function/dstr/dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/arrow-function/dstr/dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/arrow-function/dstr/dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/arrow-function/dstr/dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/arrow-function/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/arrow-function/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/async-generator/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/async-generator/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/async-generator/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/async-generator/dstr/ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/named-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/named-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/named-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/named-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/named-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/named-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/named-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/named-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/named-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/named-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/named-dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/dstr/named-dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/async-generator/named-dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/async-generator/named-dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/async-generator/named-dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/async-generator/named-params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/async-generator/named-params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/async-generator/named-yield-identifier-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/expressions/async-generator/named-yield-identifier-spread-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/expressions/async-generator/named-yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/async-generator/named-yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/async-generator/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/async-generator/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/async-generator/yield-identifier-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/expressions/async-generator/yield-identifier-spread-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/expressions/async-generator/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/async-generator/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/call/S11.2.4_A1.1_T2.js', 'function .length reflection'],
  ['test/language/expressions/call/S11.2.4_A1.2_T2.js', 'function .length reflection'],
  ['test/language/expressions/call/spread-err-mult-err-expr-throws.js', 'spread drives the iterator protocol (indexed model)'],
  ['test/language/expressions/call/spread-err-sngl-err-expr-throws.js', 'spread of an iterator value in call args (recorded __drain follow-up)'],
  ['test/language/expressions/class/async-gen-method-static/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/class/async-gen-method-static/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/class/async-gen-method/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/async-gen-method/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/async-gen-method/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/async-gen-method/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/async-gen-method/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/async-gen-method/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/class/async-gen-method/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/class/async-method/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/async-method/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/async-method/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/async-method/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/async-method/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/dstr/async-gen-meth-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-gen-meth-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-gen-meth-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-gen-meth-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-gen-meth-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-gen-meth-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-gen-meth-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-gen-meth-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-gen-meth-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-gen-meth-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-gen-meth-dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-gen-meth-dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-static-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-static-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-static-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-static-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-static-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-static-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-static-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-static-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-static-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/async-private-gen-meth-static-dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/gen-meth-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/gen-meth-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/gen-meth-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/gen-meth-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/gen-meth-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/gen-meth-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/gen-meth-static-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/gen-meth-static-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/gen-meth-static-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/gen-meth-static-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/gen-meth-static-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/gen-meth-static-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-static-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-static-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-static-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-static-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-static-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-static-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-static-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-static-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-static-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/meth-static-dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-gen-meth-static-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-gen-meth-static-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-gen-meth-static-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-gen-meth-static-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-gen-meth-static-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-gen-meth-static-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-gen-meth-static-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-gen-meth-static-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-gen-meth-static-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-gen-meth-static-dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-meth-static-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-meth-static-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-meth-static-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-meth-static-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-meth-static-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-meth-static-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-meth-static-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-meth-static-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-meth-static-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/dstr/private-meth-static-dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/class/elements/async-gen-private-method/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/class/elements/async-gen-private-method/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/class/elements/gen-private-method-static/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/class/elements/gen-private-method-static/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/class/gen-method-static/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/gen-method-static/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/gen-method-static/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/gen-method-static/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/gen-method-static/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/gen-method-static/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/class/gen-method-static/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/class/gen-method/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/gen-method/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/gen-method/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/gen-method/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/gen-method/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/gen-method/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/class/gen-method/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/class/method-static/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/method-static/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/method-static/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/method-static/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/method-static/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/method/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/method/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/method/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/method/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/method/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/class/params-dflt-gen-meth-args-unmapped.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/params-dflt-gen-meth-static-args-unmapped.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/params-dflt-meth-args-unmapped.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/params-dflt-meth-static-args-unmapped.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/class/scope-gen-meth-paramsbody-var-close.js', 'params/body/fn-name own var-environment semantics outside jzify subset'],
  ['test/language/expressions/class/scope-meth-paramsbody-var-close.js', 'params/body/fn-name own var-environment semantics outside jzify subset'],
  ['test/language/expressions/class/scope-static-gen-meth-paramsbody-var-close.js', 'audited out of the jz value model'],
  ['test/language/expressions/class/scope-static-setter-paramsbody-var-close.js', 'params/body/fn-name own var-environment semantics outside jzify subset'],
  ['test/language/expressions/function/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/function/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/function/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/function/dstr/ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/function/dstr/ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/function/dstr/ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/function/dstr/ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/function/dstr/ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/function/dstr/dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/function/dstr/dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/function/dstr/dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/function/dstr/dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/function/dstr/dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/function/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/function/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/generators/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/generators/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/generators/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/generators/dstr/ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/generators/dstr/ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/generators/dstr/ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/generators/dstr/ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/generators/dstr/ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/generators/dstr/dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/generators/dstr/dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/generators/dstr/dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/generators/dstr/dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/generators/dstr/dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/generators/named-yield-identifier-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/expressions/generators/named-yield-identifier-spread-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/expressions/generators/named-yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/generators/named-yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/generators/params-dflt-args-unmapped.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/generators/params-dflt-ref-arguments.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/generators/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/generators/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/generators/scope-name-var-close.js', 'audited out of the jz value model'],
  ['test/language/expressions/generators/scope-paramsbody-var-close.js', 'params/body/fn-name own var-environment semantics outside jzify subset'],
  ['test/language/expressions/generators/yield-as-yield-operand.js', 'audited out of the jz value model'],
  ['test/language/expressions/generators/yield-identifier-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/expressions/generators/yield-identifier-spread-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/expressions/generators/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/generators/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/new/spread-err-mult-err-expr-throws.js', 'spread of an iterator value in call args (recorded __drain follow-up)'],
  ['test/language/expressions/new/spread-err-sngl-err-expr-throws.js', 'spread of an iterator value in call args (recorded __drain follow-up)'],
  ['test/language/expressions/object/dstr/async-gen-meth-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/async-gen-meth-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/async-gen-meth-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/async-gen-meth-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/async-gen-meth-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/async-gen-meth-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/async-gen-meth-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/async-gen-meth-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/async-gen-meth-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/async-gen-meth-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/async-gen-meth-dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/async-gen-meth-dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/gen-meth-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/gen-meth-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/gen-meth-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/gen-meth-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/gen-meth-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/gen-meth-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/gen-meth-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/gen-meth-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/gen-meth-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/gen-meth-dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/meth-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/meth-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/meth-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/meth-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/meth-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/meth-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/meth-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/meth-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/meth-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/dstr/meth-dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/expressions/object/method-definition/async-gen-meth-dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/object/method-definition/async-gen-meth-dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/object/method-definition/async-gen-meth-dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/object/method-definition/async-gen-meth-params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/object/method-definition/async-gen-meth-params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/object/method-definition/async-gen-yield-identifier-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/expressions/object/method-definition/async-gen-yield-identifier-spread-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/expressions/object/method-definition/async-gen-yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/object/method-definition/async-gen-yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/object/method-definition/gen-meth-dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/object/method-definition/gen-meth-dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/object/method-definition/gen-meth-dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/object/method-definition/gen-meth-params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/object/method-definition/gen-meth-params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/object/method-definition/gen-yield-identifier-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/expressions/object/method-definition/gen-yield-identifier-spread-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/expressions/object/method-definition/gen-yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/object/method-definition/gen-yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/object/method-definition/meth-dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/object/method-definition/meth-dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/object/method-definition/meth-dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/expressions/object/method-definition/meth-params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/expressions/object/method-definition/meth-params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/expressions/object/method-definition/params-dflt-gen-meth-args-unmapped.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/object/method-definition/params-dflt-gen-meth-ref-arguments.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/object/method-definition/params-dflt-meth-args-unmapped.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/object/method-definition/params-dflt-meth-ref-arguments.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/object/method-definition/yield-as-yield-operand.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/expressions/object/scope-gen-meth-paramsbody-var-close.js', 'params/body/fn-name own var-environment semantics outside jzify subset'],
  ['test/language/expressions/yield/arguments-object-attributes.js', 'audited out of the jz value model'],
  ['test/language/expressions/yield/formal-parameters-after-reassignment-non-strict.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/expressions/yield/rhs-regexp.js', 'regex method dispatch through untyped carriers (recorded)'],
  ['test/language/expressions/yield/rhs-yield.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/rest-parameters/expected-argument-count.js', 'audited out of the jz value model'],
  ['test/language/statements/async-generator/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/async-generator/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/async-generator/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/statements/async-generator/dstr/ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/async-generator/dstr/ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/async-generator/dstr/ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/async-generator/dstr/ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/async-generator/dstr/ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/async-generator/dstr/ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/async-generator/dstr/dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/async-generator/dstr/dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/async-generator/dstr/dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/async-generator/dstr/dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/async-generator/dstr/dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/async-generator/dstr/dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/async-generator/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/statements/async-generator/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/statements/async-generator/yield-identifier-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/statements/async-generator/yield-identifier-spread-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/statements/async-generator/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/async-generator/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/async-gen-method-static/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/async-gen-method-static/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/async-gen-method/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/async-gen-method/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/async-gen-method/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/async-gen-method/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/async-gen-method/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/async-gen-method/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/async-gen-method/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/async-method/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/async-method/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/async-method/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/async-method/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/async-method/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/definition/methods-gen-yield-as-yield-operand.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/dstr/async-gen-meth-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-gen-meth-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-gen-meth-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-gen-meth-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-gen-meth-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-gen-meth-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-gen-meth-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-gen-meth-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-gen-meth-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-gen-meth-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-gen-meth-dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-gen-meth-dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-static-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-static-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-static-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-static-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-static-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-static-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-static-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-static-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-static-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/async-private-gen-meth-static-dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/gen-meth-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/gen-meth-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/gen-meth-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/gen-meth-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/gen-meth-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/gen-meth-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/gen-meth-static-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/gen-meth-static-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/gen-meth-static-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/gen-meth-static-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/gen-meth-static-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/gen-meth-static-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-static-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-static-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-static-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-static-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-static-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-static-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-static-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-static-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-static-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/meth-static-dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-gen-meth-static-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-gen-meth-static-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-gen-meth-static-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-gen-meth-static-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-gen-meth-static-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-gen-meth-static-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-gen-meth-static-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-gen-meth-static-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-gen-meth-static-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-gen-meth-static-dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-meth-static-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-meth-static-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-meth-static-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-meth-static-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-meth-static-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-meth-static-dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-meth-static-dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-meth-static-dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-meth-static-dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/dstr/private-meth-static-dflt-ary-ptrn-rest-id-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/class/elements/async-gen-private-method/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/elements/async-gen-private-method/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/elements/gen-private-method-static/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/elements/gen-private-method-static/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/gen-method-static/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/gen-method-static/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/gen-method-static/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/gen-method-static/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/gen-method-static/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/gen-method-static/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/gen-method-static/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/gen-method/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/gen-method/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/gen-method/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/gen-method/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/gen-method/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/gen-method/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/gen-method/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/class/method-static/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/method-static/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/method-static/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/method-static/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/method-static/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/method/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/method/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/method/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/method/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/method/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/statements/class/params-dflt-gen-meth-args-unmapped.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/params-dflt-gen-meth-static-args-unmapped.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/params-dflt-meth-args-unmapped.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/params-dflt-meth-static-args-unmapped.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/class/scope-gen-meth-paramsbody-var-close.js', 'params/body/fn-name own var-environment semantics outside jzify subset'],
  ['test/language/statements/class/scope-meth-paramsbody-var-close.js', 'params/body/fn-name own var-environment semantics outside jzify subset'],
  ['test/language/statements/class/scope-static-gen-meth-paramsbody-var-close.js', 'params/body/fn-name own var-environment semantics outside jzify subset'],
  ['test/language/statements/class/scope-static-setter-paramsbody-var-close.js', 'params/body/fn-name own var-environment semantics outside jzify subset'],
  ['test/language/statements/const/dstr/ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/const/dstr/ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/const/dstr/ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/const/dstr/ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/const/dstr/ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/const-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/const-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/const-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/const-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/const-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/let-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/let-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/let-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/let-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/let-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/var-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/var-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/var-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/var-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for-of/dstr/var-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/const-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/const-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/const-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/const-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/const-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/let-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/let-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/let-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/let-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/let-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/var-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/var-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/var-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/for/dstr/var-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/function/S13.2_A3.js', 'function .length reflection'],
  ['test/language/statements/function/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/function/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/function/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/statements/function/dstr/ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/function/dstr/ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/function/dstr/ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/function/dstr/ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/function/dstr/ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/function/dstr/dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/function/dstr/dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/function/dstr/dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/function/dstr/dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/function/dstr/dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/function/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/statements/function/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/statements/generators/dflt-params-ref-later.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/generators/dflt-params-ref-self.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/generators/dflt-params-trailing-comma.js', 'function .length reflection unsupported'],
  ['test/language/statements/generators/dstr/ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/generators/dstr/ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/generators/dstr/ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/generators/dstr/ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/generators/dstr/ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/generators/dstr/dflt-ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/generators/dstr/dflt-ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/generators/dstr/dflt-ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/generators/dstr/dflt-ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/generators/dstr/dflt-ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/generators/params-dflt-args-unmapped.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/generators/params-dflt-ref-arguments.js', 'arguments/default-param scope reflection outside jz scope'],
  ['test/language/statements/generators/params-trailing-comma-multiple.js', 'function .length reflection unsupported'],
  ['test/language/statements/generators/params-trailing-comma-single.js', 'function .length reflection unsupported'],
  ['test/language/statements/generators/scope-paramsbody-var-close.js', 'params/body/fn-name own var-environment semantics outside jzify subset'],
  ['test/language/statements/generators/yield-as-yield-operand.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/generators/yield-identifier-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/statements/generators/yield-identifier-spread-non-strict.js', 'yield as an identifier (reserved in the jz subset)'],
  ['test/language/statements/generators/yield-spread-arr-multiple.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/generators/yield-spread-arr-single.js', 'yield in arbitrary expression positions (v1 machine surface)'],
  ['test/language/statements/let/dstr/ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/let/dstr/ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/let/dstr/ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/let/dstr/ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/let/dstr/ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/try/dstr/ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/try/dstr/ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/try/dstr/ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/try/dstr/ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/try/dstr/ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/variable/dstr/ary-ptrn-elem-ary-elision-init.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/variable/dstr/ary-ptrn-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/variable/dstr/ary-ptrn-rest-ary-elision.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/variable/dstr/ary-ptrn-rest-ary-empty.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
  ['test/language/statements/variable/dstr/ary-ptrn-rest-id-elision-next-err.js', 'array-pattern elision/rest ride the iterator protocol (jz destructures by index)'],
])
