// fft.js — iterative radix-2 Cooley–Tukey FFT (decimation-in-time), in place,
// over real input. The single most standard numeric kernel; the per-pass
// butterfly inner loop is pure f64 +/−/× over a precomputed twiddle table — the
// shape jz vectorizes and where V8 can't from plain JS.
//
// Bit-exactness across every engine and native target is the design constraint:
//   - the twiddle table is built transcendental-free, from an in-source Taylor
//     sin/cos of the base angle 2π/N (libm Math.sin differs per platform), then
//     a complex recurrence — so the table is identical everywhere.
//   - the butterflies are +/−/×; with FMA contraction off they are bit-identical.
//     Go's arm64 backend force-fuses a*b+c → its checksum is the documented `fma`
//     parity class (same as biquad), not a divergence.
//
// Single source compiled by all targets (jz, porffor, jawsm) and run directly by
// the JS engines. Subset: const/let + arrows, Float64Array, no class/async/regex.
//
// Reports: median ms across N_RUNS, throughput in butterflies/µs, FNV-1a checksum
// over the transformed real part.

import { checksumF64, medianUs, printResult } from '../_lib/benchlib.js'

const N = 1 << 16        // transform size (power of two): 65536
const LOG2N = 16
const N_RUNS = 21
const N_WARMUP = 5

// --- transcendental-free trig (Taylor, Horner form, no libm) ---------------
// Accurate to ~1e-13 for the small base angle |2π/N|, and bit-identical across
// languages because it is the same sequence of f64 +/× in each.
const sinPoly = (x) => {
  const x2 = x * x
  return x * (1 + x2 * (-0.16666666666666666 + x2 * (0.008333333333333333 + x2 * (-0.0001984126984126984 + x2 * (2.7557319223985893e-06 + x2 * -2.505210838544172e-08)))))
}
const cosPoly = (x) => {
  const x2 = x * x
  return 1 + x2 * (-0.5 + x2 * (0.041666666666666664 + x2 * (-0.001388888888888889 + x2 * (2.48015873015873e-05 + x2 * -2.7557319223985894e-07))))
}

// Twiddles W_k = exp(-i·2πk/N) = (cos(2πk/N), -sin(2πk/N)) for k in [0, N/2),
// generated by complex recurrence from W_1 so no per-k transcendental is needed.
const buildTwiddles = (wre, wim, n) => {
  const dt = -6.283185307179586 / n      // -2π/N (forward transform)
  const c1 = cosPoly(dt), s1 = sinPoly(dt)
  let cr = 1, ci = 0
  const half = n >> 1
  for (let k = 0; k < half; k++) {
    wre[k] = cr
    wim[k] = ci
    const nr = cr * c1 - ci * s1
    const ni = cr * s1 + ci * c1
    cr = nr
    ci = ni
  }
}

const fft = (re, im, wre, wim, n) => {
  // in-place bit-reversal permutation
  for (let i = 1, j = 0; i < n; i++) {
    let bit = n >> 1
    for (; j & bit; bit >>= 1) j ^= bit
    j ^= bit
    if (i < j) {
      const tr = re[i]; re[i] = re[j]; re[j] = tr
      const ti = im[i]; im[i] = im[j]; im[j] = ti
    }
  }
  // log2(n) butterfly passes
  for (let len = 2; len <= n; len <<= 1) {
    const half = len >> 1
    const step = (n / len) | 0
    for (let i = 0; i < n; i += len) {
      for (let j = 0, k = 0; j < half; j++, k += step) {
        const wr = wre[k], wi = wim[k]
        const a = i + j, b = a + half
        const xr = re[b], xi = im[b]
        const tr = wr * xr - wi * xi
        const ti = wr * xi + wi * xr
        re[b] = re[a] - tr
        im[b] = im[a] - ti
        re[a] = re[a] + tr
        im[a] = im[a] + ti
      }
    }
  }
}

// Deterministic real input in [-1, 1) — XorShift32, bit-identical per target.
const mkSignal = (n) => {
  const out = new Float64Array(n)
  let s = 0x1234abcd | 0
  for (let i = 0; i < n; i++) {
    s ^= s << 13
    s ^= s >>> 17
    s ^= s << 5
    out[i] = ((s >>> 0) / 4294967296) * 2 - 1
  }
  return out
}

export let main = () => {
  const sig = mkSignal(N)
  const re = new Float64Array(N)
  const im = new Float64Array(N)
  const wre = new Float64Array(N >> 1)
  const wim = new Float64Array(N >> 1)
  buildTwiddles(wre, wim, N)

  const reset = () => {
    for (let i = 0; i < N; i++) { re[i] = sig[i]; im[i] = 0 }
  }

  for (let i = 0; i < N_WARMUP; i++) { reset(); fft(re, im, wre, wim, N) }

  const samples = new Float64Array(N_RUNS)
  for (let i = 0; i < N_RUNS; i++) {
    reset()
    const t0 = performance.now()
    fft(re, im, wre, wim, N)
    samples[i] = performance.now() - t0
  }
  printResult(medianUs(samples), checksumF64(re), (N * LOG2N) >> 1, LOG2N, N_RUNS)
}
